In [1]:
## Pandas is a poweful data manipulation library in Python, widely used for data analysis and data cleaning.

## It provides two primary data structures: Series and Data frame.

## A Series is a one- dimensional array like object, while a Data frame is a two dimensional, size-mutable and potentially heterogeneous tabular data structure with labeled axes
## (rows and columns).

In [2]:
import pandas as pd

In [3]:
## Series

## A Pandas - Series is one dimensional array - like object that can hold any data type.
## It is similar to  column in a table.

In [10]:
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series:\n",series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [8]:
## Create series from ditionary

data = {'a':1,'b':2,'c':3,'d':4,'e':5}

series_dict = pd.Series(data)

print("Series_dict:\n",series_dict)
print(type(series_dict))

Series_dict:
 a    1
b    2
c    3
d    4
e    5
dtype: int64
<class 'pandas.Series'>

In [12]:
data = [10,20,30]

index = ['a','b','c']

s = pd.Series(data,index=index)

print(type(s))

<class 'pandas.Series'>

In [13]:
## Data Frame

In [21]:
## Create a data frame from a dictionary of list

data = {
    "Name":["Chandru","Lokesh","Hari Krishna"],
    "Age":[24,25,24],
    "Location":["IND","USA",'UK']
}

df = pd.DataFrame(data)

print(df)

print(type(df))

           Name  Age Location
0       Chandru   24      IND
1        Lokesh   25      USA
2  Hari Krishna   24       UK
<class 'pandas.DataFrame'>

In [22]:
## Create a data frame from a list of dictionaries

data = [

    {"Name":"Chandru","Age":24,"Location":"IND"},
    {"Name":"Hari Krishna","Age":25,"Location":"UK"},
    {"Name":"Lokesh","Age":26,"Location":"USA"}

]

df = pd.DataFrame(data)

print(df)

           Name  Age Location
0       Chandru   24      IND
1  Hari Krishna   25       UK
2        Lokesh   26      USA

In [23]:
dataset = pd.read_csv(r"D:\Data_Analyst_Workspace\Data_Analysis_Python\data.csv")

In [24]:
dataset.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [25]:
## Accessing data from data frame

In [26]:
data

[{'Name': 'Chandru', 'Age': 24, 'Location': 'IND'},
 {'Name': 'Hari Krishna', 'Age': 25, 'Location': 'UK'},
 {'Name': 'Lokesh', 'Age': 26, 'Location': 'USA'}]

In [27]:
df

           Name  Age Location
0       Chandru   24      IND
1  Hari Krishna   25       UK
2        Lokesh   26      USA

In [28]:
df["Name"]

0         Chandru
1    Hari Krishna
2          Lokesh
Name: Name, dtype: str

In [29]:
type(df["Name"])

pandas.Series

In [33]:
df.loc[0]

Name        Chandru
Age              24
Location        IND
Name: 0, dtype: object

In [40]:
df.iloc[0]

Name        Chandru
Age              24
Location        IND
Name: 0, dtype: object

In [41]:
## Accessing the specified elements

In [42]:
df["Name"]

0         Chandru
1    Hari Krishna
2          Lokesh
Name: Name, dtype: str

In [43]:
df.head()

           Name  Age Location
0       Chandru   24      IND
1  Hari Krishna   25       UK
2        Lokesh   26      USA

In [44]:
df.at[1,"Age"]

np.int64(25)

In [47]:
df.at[0,'Age']

np.int64(24)

In [48]:
df.at[2,"Name"]

'Lokesh'

In [49]:
df.iat[2,2]

'USA'

In [50]:
df.iat[2,0]

'Lokesh'

In [51]:
df

           Name  Age Location
0       Chandru   24      IND
1  Hari Krishna   25       UK
2        Lokesh   26      USA

In [52]:
## Data manipulation with dataframe

In [54]:
## Adding a column

In [53]:
df["Salary"] = [50000,60000,70000]

In [55]:
df

           Name  Age Location  Salary
0       Chandru   24      IND   50000
1  Hari Krishna   25       UK   60000
2        Lokesh   26      USA   70000

In [57]:
## (removing) = Dropping a column

In [56]:
df.drop("Salary",axis=1)

           Name  Age Location
0       Chandru   24      IND
1  Hari Krishna   25       UK
2        Lokesh   26      USA

In [58]:
df

           Name  Age Location  Salary
0       Chandru   24      IND   50000
1  Hari Krishna   25       UK   60000
2        Lokesh   26      USA   70000

In [59]:
## Permanently delete or dropping the specific column or removing the column

df.drop("Salary",axis=1,inplace=True)

In [60]:
df

           Name  Age Location
0       Chandru   24      IND
1  Hari Krishna   25       UK
2        Lokesh   26      USA

In [61]:
df["Age"] = df["Age"]+1

In [62]:
df

           Name  Age Location
0       Chandru   25      IND
1  Hari Krishna   26       UK
2        Lokesh   27      USA

In [63]:
df.head()

           Name  Age Location
0       Chandru   25      IND
1  Hari Krishna   26       UK
2        Lokesh   27      USA

In [64]:
df.dtypes

Name          str
Age         int64
Location      str
dtype: object

In [68]:
df.describe(include='all')

           Name   Age Location
count         3   3.0        3
unique        3   NaN        3
top     Chandru   NaN      IND
freq          1   NaN        1
mean        NaN  26.0      NaN
std         NaN   1.0      NaN
min         NaN  25.0      NaN
25%         NaN  25.5      NaN
50%         NaN  26.0      NaN
75%         NaN  26.5      NaN
max         NaN  27.0      NaN

In [67]:
dataset.describe(include='all')

              Date Category      Value   Product       Sales Region
count           50       50  47.000000        50   46.000000     50
unique          50        3        NaN         3         NaN      4
top     2023-01-01        C        NaN  Product3         NaN   West
freq             1       21        NaN        19         NaN     18
mean           NaN      NaN  51.744681       NaN  557.130435    NaN
std            NaN      NaN  29.050532       NaN  274.598584    NaN
min            NaN      NaN   2.000000       NaN  108.000000    NaN
25%            NaN      NaN  27.500000       NaN  339.000000    NaN
50%            NaN      NaN  54.000000       NaN  591.500000    NaN
75%            NaN      NaN  70.000000       NaN  767.500000    NaN
max            NaN      NaN  99.000000       NaN  992.000000    NaN